// <auto-generated />
using System;
using JustBlog.Core.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JustBlog.Core.Migrations
{
    [DbContext(typeof(JustBlogContext))]
    [Migration("20230615091103_v1")]
    partial class v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("JustBlog.Core.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AboutMe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3cd9f771-f6e6-4c55-94ec-824b86c6b95a"),
                            AboutMe = "Welcome to my blogs",
                            AccessFailedCount = 0,
                            Age = 20,
                            ConcurrencyStamp = "08ccb1dd-e166-45d0-8008-a49b27d3c05f",
                            Email = "ngoccm@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "NGOCCM@GMAIL.COM",
                            NormalizedUserName = "NGOCCM@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEBmRa41UFlzSxs2lusvWD3kmGA7QSqk3Xy+B+kjqtAtejSs4Ewr8rPu8raqajUHg7A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f955c3b6-86d9-47a2-8994-ad91cafa91a8",
                            TwoFactorEnabled = false,
                            UserName = "ngoccm@gmail.com"
                        },
                        new
                        {
                            Id = new Guid("bc73dbef-1bf7-4c2f-9077-3d991b9dcb56"),
                            AboutMe = "Welcome to my blogs",
                            AccessFailedCount = 0,
                            Age = 20,
                            ConcurrencyStamp = "b044f4a1-149e-44e4-a247-bff3751c18dc",
                            Email = "ngoccm1@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "NGOCCM1@GMAIL.COM",
                            NormalizedUserName = "NGOCCM1@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEFjk9pA3/yvOdmNK316awB/D4kw8Mgs7Wz079M7wjtJyI/FcBYtfY0Pov8pbH5qZjQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "19a81c7a-6ac6-4235-9d08-7a4c72ea0b77",
                            TwoFactorEnabled = false,
                            UserName = "ngoccm1@gmail.com"
                        },
                        new
                        {
                            Id = new Guid("3fb38b96-29ec-4ccf-a988-8f85c55460f7"),
                            AboutMe = "Welcome to my blogs",
                            AccessFailedCount = 0,
                            Age = 20,
                            ConcurrencyStamp = "4e47ca1b-d1fa-4867-9021-38a47cdceeec",
                            Email = "ngoccm2@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "NGOCCM2@GMAIL.COM",
                            NormalizedUserName = "NGOCCM2@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEJLp/M7pdTcPK9cpI2+h6LmYVNkZBCyXNf5k7KhLGWuL4Rr6ok6Or5EmJpDphonTJg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "44a3a7da-cf70-4165-9120-1fe2bec964c4",
                            TwoFactorEnabled = false,
                            UserName = "ngoccm2@gmail.com"
                        });
                });

            modelBuilder.Entity("JustBlog.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UrlSlug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The latest news and updates on technology",
                            Name = "Technology",
                            UrlSlug = "technology"
                        },
                        new
                        {
                            Id = 2,
                            Description = "All about sports from around the world",
                            Name = "Sports",
                            UrlSlug = "sports"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Movies, TV shows, music, and more",
                            Name = "Entertainment",
                            UrlSlug = "entertainment"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Discover new destinations and plan your next trip",
                            Name = "Travel",
                            UrlSlug = "travel"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Delicious recipes and restaurant recommendations",
                            Name = "Food",
                            UrlSlug = "food"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Tips and tricks for a healthy lifestyle",
                            Name = "Health and Fitness",
                            UrlSlug = "health-and-fitness"
                        });
                });

            modelBuilder.Entity("JustBlog.Core.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CommentHeader")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CommentTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Comments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommentHeader = "Great post!",
                            CommentText = "Thanks for the informative article.",
                            CommentTime = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john.doe@gmail.com",
                            Name = "John Doe",
                            PostId = 4
                        },
                        new
                        {
                            Id = 2,
                            CommentHeader = "Interesting read",
                            CommentText = "I learned a lot from this post.",
                            CommentTime = new DateTime(2022, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jane.smith@gmail.com",
                            Name = "Jane Smith",
                            PostId = 3
                        },
                        new
                        {
                            Id = 3,
                            CommentHeader = "Helpful tips",
                            CommentText = "This post was very useful.",
                            CommentTime = new DateTime(2022, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bob.johnson@gmail.com",
                            Name = "Bob Johnson",
                            PostId = 3
                        },
                        new
                        {
                            Id = 4,
                            CommentHeader = "Well written",
                            CommentText = "I enjoyed reading this post.",
                            CommentTime = new DateTime(2022, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sarah.lee@gmail.com",
                            Name = "Sarah Lee",
                            PostId = 7
                        },
                        new
                        {
                            Id = 5,
                            CommentHeader = "Insightful",
                            CommentText = "This post gave me a new perspective.",
                            CommentTime = new DateTime(2022, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "michael.chen@gmail.com",
                            Name = "Michael Chen",
                            PostId = 5
                        },
                        new
                        {
                            Id = 6,
                            CommentHeader = "Good job",
                            CommentText = "Keep up the great work!",
                            CommentTime = new DateTime(2021, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "grace.kim@gmail.com",
                            Name = "Grace Kim",
                            PostId = 1
                        },
                        new
                        {
                            Id = 7,
                            CommentHeader = "Impressive",
                            CommentText = "I'm amazed by the quality of this post.",
                            CommentTime = new DateTime(2022, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "david.wu@gmail.com",
                            Name = "David Wu",
                            PostId = 5
                        },
                        new
                        {
                            Id = 8,
                            CommentHeader = "Thank you",
                            CommentText = "Your post helped me solve a problem.",
                            CommentTime = new DateTime(2022, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emily.park@gmail.com",
                            Name = "Emily Park",
                            PostId = 2
                        },
                        new
                        {
                            Id = 9,
                            CommentHeader = "Informative",
                            CommentText = "I learned something new from this post.",
                            CommentTime = new DateTime(2021, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "alex.nguyen@gmail.com",
                            Name = "Alex Nguyen",
                            PostId = 2
                        },
                        new
                        {
                            Id = 10,
                            CommentHeader = "Well done",
                            CommentText = "This post was well researched and written.",
                            CommentTime = new DateTime(2022, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lisa.wang@gmail.com",
                            Name = "Lisa Wang",
                            PostId = 6
                        });
                });

            modelBuilder.Entity("JustBlog.Core.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("PostContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Post Content");

                    b.Property<DateTime>("PostedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("Posted On");

                    b.Property<bool>("Published")
                        .HasColumnType("bit");

                    b.Property<int>("RateCount")
                        .HasColumnType("int");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("Short Description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalRate")
                        .HasColumnType("int");

                    b.Property<string>("UrlSlug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Posts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Modified = new DateTime(2020, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "A lot of people think that having a smart home means having to spend thousands of dollars on fancy equipment. But that's not the case at all! There are plenty of affordable and easy-to-use gadgets out there that can help you make your home smarter, without breaking the bank.",
                            PostedOn = new DateTime(2018, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = true,
                            RateCount = 22631,
                            ShortDescription = "Discover the latest smart home gadgets that you need!",
                            Title = "Top 10 Gadgets to Make Your Home Smarter",
                            TotalRate = 67723,
                            UrlSlug = "top-10-gadgets-to-make-your-home-smarter",
                            ViewCount = 3142
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Modified = new DateTime(2020, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Are you tired of looking at the same old boring walls in your room? It's time to spruce things up and add some personality to your space. Here are 10 easy ways to decorate your room that won't cost you an arm and a leg!",
                            PostedOn = new DateTime(2019, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = true,
                            RateCount = 36841,
                            ShortDescription = "Get inspiration for your next DIY project!",
                            Title = "10 Easy Ways to Decorate Your Room",
                            TotalRate = 83123,
                            UrlSlug = "10-easy-ways-to-decorate-your-room",
                            ViewCount = 42203
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Modified = new DateTime(2021, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "There's nothing quite like a perfectly cooked steak. Juicy, tender, and full of flavor… it's no wonder that steak is one of the most beloved foods out there. But cooking a steak to perfection isn't always easy. Here are some tips and tricks to help you cook the perfect steak every time!",
                            PostedOn = new DateTime(2016, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = true,
                            RateCount = 54068,
                            ShortDescription = "Learn the art of cooking steak like a pro!",
                            Title = "How to Cook a Perfect Steak",
                            TotalRate = 236421,
                            UrlSlug = "how-to-cook-a-perfect-steak",
                            ViewCount = 65173
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Modified = new DateTime(2021, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "If you're a fashionista, you know it's important to stay on top of the latest trends. And with a new year comes a whole new set of fashion trends to try out! From bold colors to oversized accessories, here are the fashion trends you need to follow in 2021.",
                            PostedOn = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = false,
                            RateCount = 65381,
                            ShortDescription = "Get ready to update your wardrobe!",
                            Title = "Fashion Trends You Need to Follow in 2021",
                            TotalRate = 214823,
                            UrlSlug = "fashion-trends-you-need-to-follow-in-2021",
                            ViewCount = 76437
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            Modified = new DateTime(2021, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Europe is home to some of the most stunning and iconic destinations in the world. Whether you're looking for vibrant cities, breathtaking landscapes, or rich cultural experiences, Europe has it all. Here are 10 amazing places in Europe that you won't want to miss!",
                            PostedOn = new DateTime(2017, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = true,
                            RateCount = 10631,
                            ShortDescription = "Get your passport ready!",
                            Title = "10 Amazing Places to Visit in Europe",
                            TotalRate = 42389,
                            UrlSlug = "10-amazing-places-to-visit-in-europe",
                            ViewCount = 23142
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 6,
                            Modified = new DateTime(2020, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "In today's fast-paced and stressful world, it's more important than ever to take care of your mental health. Fortunately, there are plenty of simple things that you can do to reduce stress and improve your mental wellbeing. Here are some tips to get you started!",
                            PostedOn = new DateTime(2018, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = true,
                            RateCount = 64234,
                            ShortDescription = "Take care of your mental health!",
                            Title = "Mental Health Tips for a Stress-Free Life",
                            TotalRate = 116196,
                            UrlSlug = "mental-health-tips-for-a-stress-free-life",
                            ViewCount = 87631
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Modified = new DateTime(2021, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Do you love coffee but can't seem to make a good cup at home? Don't worry, you're not alone. Making the perfect cup of coffee is an art, and it takes time and practice to get it just right. But with these tips, you'll be well on your way to becoming a coffee expert!",
                            PostedOn = new DateTime(2019, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = false,
                            RateCount = 54172,
                            ShortDescription = "Become a barista in your own home!",
                            Title = "How to Make the Perfect Cup of Coffee",
                            TotalRate = 195701,
                            UrlSlug = "how-to-make-the-perfect-cup-of-coffee",
                            ViewCount = 76853
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Modified = new DateTime(2022, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Learning a new language is not just about being able to communicate with people from different countries, it's also about opening up new doors of opportunity in your personal and professional life. Whether you want to travel, work abroad or simply broaden your mind, knowing more than one language can be incredibly useful. Research has shown that bilingualism can improve cognitive abilities such as problem-solving and decision-making. So, what are you waiting for? Start learning a new language today!",
                            PostedOn = new DateTime(2021, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = true,
                            RateCount = 30230,
                            ShortDescription = "In today's globalized world, learning a new language can unlock many opportunities.",
                            Title = "Why You Should Learn a New Language",
                            TotalRate = 148341,
                            UrlSlug = "why-you-should-learn-a-new-language",
                            ViewCount = 55230
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 6,
                            Modified = new DateTime(2019, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Regular exercise has been shown to have numerous benefits for both physical and mental health. It can help you maintain a healthy weight, reduce your risk of chronic diseases such as diabetes and heart disease, and improve your overall mood and wellbeing. Studies have also suggested that exercise can boost cognitive function and reduce the risk of age-related cognitive decline. So, whether you prefer jogging, cycling, swimming or yoga, make sure to incorporate regular exercise into your daily routine!",
                            PostedOn = new DateTime(2019, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = true,
                            RateCount = 84124,
                            ShortDescription = "Exercising regularly can have a positive impact on both physical and mental health.",
                            Title = "The Benefits of Regular Exercise",
                            TotalRate = 374049,
                            UrlSlug = "the-benefits-of-regular-exercise",
                            ViewCount = 74263
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 6,
                            Modified = new DateTime(2023, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostContent = "Mindfulness meditation is a simple but powerful technique that involves focusing your attention on the present moment, without judgment. It has been shown to have numerous benefits for mental and physical health, including reducing stress, anxiety, and depression, improving sleep quality, and enhancing immune function. To start practicing mindfulness meditation, find a quiet place where you can sit comfortably, close your eyes, and focus on your breath. If your mind starts to wander, gently bring your attention back to your breath. With regular practice, mindfulness meditation can help you cultivate a greater sense of calm and clarity in your daily life.",
                            PostedOn = new DateTime(2023, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = true,
                            RateCount = 51426,
                            ShortDescription = "Practicing mindfulness meditation can help reduce stress and improve overall wellbeing.",
                            Title = "The Power of Mindfulness Meditation",
                            TotalRate = 181574,
                            UrlSlug = "the-power-of-mindfulness-meditation",
                            ViewCount = 68230
                        });
                });

            modelBuilder.Entity("JustBlog.Core.Entities.PostTagMap", b =>
                {
                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.HasKey("TagId", "PostId");

                    b.HasIndex("PostId");

                    b.ToTable("PostTagMaps", (string)null);

                    b.HasData(
                        new
                        {
                            TagId = 1,
                            PostId = 1
                        },
                        new
                        {
                            TagId = 4,
                            PostId = 1
                        },
                        new
                        {
                            TagId = 5,
                            PostId = 1
                        },
                        new
                        {
                            TagId = 3,
                            PostId = 2
                        },
                        new
                        {
                            TagId = 6,
                            PostId = 2
                        },
                        new
                        {
                            TagId = 2,
                            PostId = 3
                        },
                        new
                        {
                            TagId = 5,
                            PostId = 3
                        },
                        new
                        {
                            TagId = 1,
                            PostId = 4
                        },
                        new
                        {
                            TagId = 4,
                            PostId = 4
                        },
                        new
                        {
                            TagId = 2,
                            PostId = 5
                        },
                        new
                        {
                            TagId = 3,
                            PostId = 5
                        },
                        new
                        {
                            TagId = 5,
                            PostId = 5
                        },
                        new
                        {
                            TagId = 1,
                            PostId = 6
                        },
                        new
                        {
                            TagId = 4,
                            PostId = 6
                        },
                        new
                        {
                            TagId = 6,
                            PostId = 6
                        },
                        new
                        {
                            TagId = 3,
                            PostId = 7
                        },
                        new
                        {
                            TagId = 4,
                            PostId = 7
                        },
                        new
                        {
                            TagId = 2,
                            PostId = 8
                        },
                        new
                        {
                            TagId = 4,
                            PostId = 8
                        },
                        new
                        {
                            TagId = 5,
                            PostId = 9
                        },
                        new
                        {
                            TagId = 6,
                            PostId = 9
                        },
                        new
                        {
                            TagId = 1,
                            PostId = 10
                        },
                        new
                        {
                            TagId = 2,
                            PostId = 10
                        },
                        new
                        {
                            TagId = 5,
                            PostId = 10
                        },
                        new
                        {
                            TagId = 13,
                            PostId = 1
                        },
                        new
                        {
                            TagId = 15,
                            PostId = 2
                        },
                        new
                        {
                            TagId = 12,
                            PostId = 3
                        },
                        new
                        {
                            TagId = 16,
                            PostId = 7
                        },
                        new
                        {
                            TagId = 16,
                            PostId = 8
                        },
                        new
                        {
                            TagId = 10,
                            PostId = 9
                        },
                        new
                        {
                            TagId = 16,
                            PostId = 6
                        });
                });

            modelBuilder.Entity("JustBlog.Core.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UrlSlug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Count = 50,
                            Description = "All about the latest tech news and gadgets",
                            Name = "Technology",
                            UrlSlug = "technology"
                        },
                        new
                        {
                            Id = 2,
                            Count = 30,
                            Description = "Tips and tricks on how to live life to the fullest",
                            Name = "Lifestyle",
                            UrlSlug = "lifestyle"
                        },
                        new
                        {
                            Id = 3,
                            Count = 20,
                            Description = "Mouth-watering recipes and food reviews",
                            Name = "Food",
                            UrlSlug = "food"
                        },
                        new
                        {
                            Id = 4,
                            Count = 25,
                            Description = "The latest trends in the world of fashion",
                            Name = "Fashion",
                            UrlSlug = "fashion"
                        },
                        new
                        {
                            Id = 5,
                            Count = 40,
                            Description = "Amazing destinations and travel guides",
                            Name = "Travel",
                            UrlSlug = "travel"
                        },
                        new
                        {
                            Id = 6,
                            Count = 15,
                            Description = "Informational articles on mental and physical wellbeing",
                            Name = "Health",
                            UrlSlug = "health"
                        },
                        new
                        {
                            Id = 7,
                            Count = 19,
                            Description = "Strategies for advancing your career and achieving your goals",
                            Name = "Career Development",
                            UrlSlug = "career-development"
                        },
                        new
                        {
                            Id = 8,
                            Count = 27,
                            Description = "Ideas and inspiration for decorating your home",
                            Name = "Home Decor",
                            UrlSlug = "home-decor"
                        },
                        new
                        {
                            Id = 9,
                            Count = 11,
                            Description = "Insights and research on human behavior and mental processes",
                            Name = "Psychology",
                            UrlSlug = "psychology"
                        },
                        new
                        {
                            Id = 10,
                            Count = 16,
                            Description = "Exploring the cultural significance of food and cuisine",
                            Name = "Food Culture",
                            UrlSlug = "food-culture"
                        },
                        new
                        {
                            Id = 11,
                            Count = 13,
                            Description = "Motivation and inspiration for staying fit and active",
                            Name = "Fitness Inspiration",
                            UrlSlug = "fitness-inspiration"
                        },
                        new
                        {
                            Id = 12,
                            Count = 28,
                            Description = "Coverage of the latest sports news and events",
                            Name = "Sports News",
                            UrlSlug = "sports-news"
                        },
                        new
                        {
                            Id = 13,
                            Count = 21,
                            Description = "Exploring the art and science of cooking and gastronomy",
                            Name = "Culinary Arts",
                            UrlSlug = "culinary-arts"
                        },
                        new
                        {
                            Id = 14,
                            Count = 16,
                            Description = "Insights and strategies for leveraging digital channels to reach customers",
                            Name = "Digital Marketing",
                            UrlSlug = "digital-marketing"
                        },
                        new
                        {
                            Id = 15,
                            Count = 19,
                            Description = "Practical advice for building healthy and fulfilling relationships",
                            Name = "Relationship Advice",
                            UrlSlug = "relationship-advice"
                        },
                        new
                        {
                            Id = 16,
                            Count = 12,
                            Description = "Tips and recommendations for outdoor activities and exploration",
                            Name = "Outdoor Adventures",
                            UrlSlug = "outdoor-adventures"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("83b38610-00bd-4593-b663-cefbd7d260cf"),
                            ConcurrencyStamp = "81e9c20a-be8e-4d15-89ef-240e27c1aa02",
                            Name = "Blog Owner",
                            NormalizedName = "BLOG OWNER"
                        },
                        new
                        {
                            Id = new Guid("3d59be22-6814-4fbf-9b46-99539b04222d"),
                            ConcurrencyStamp = "600d512e-2649-4047-889e-53882cb44beb",
                            Name = "Contributor",
                            NormalizedName = "CONTRIBUTOR"
                        },
                        new
                        {
                            Id = new Guid("3764eb80-b651-4d6f-a2e5-c539322921a5"),
                            ConcurrencyStamp = "a531b543-b012-44a1-8511-3fd22f53f374",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("3cd9f771-f6e6-4c55-94ec-824b86c6b95a"),
                            RoleId = new Guid("83b38610-00bd-4593-b663-cefbd7d260cf")
                        },
                        new
                        {
                            UserId = new Guid("bc73dbef-1bf7-4c2f-9077-3d991b9dcb56"),
                            RoleId = new Guid("3d59be22-6814-4fbf-9b46-99539b04222d")
                        },
                        new
                        {
                            UserId = new Guid("3fb38b96-29ec-4ccf-a988-8f85c55460f7"),
                            RoleId = new Guid("3764eb80-b651-4d6f-a2e5-c539322921a5")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("JustBlog.Core.Entities.Comment", b =>
                {
                    b.HasOne("JustBlog.Core.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("JustBlog.Core.Entities.Post", b =>
                {
                    b.HasOne("JustBlog.Core.Entities.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("JustBlog.Core.Entities.PostTagMap", b =>
                {
                    b.HasOne("JustBlog.Core.Entities.Post", "Post")
                        .WithMany("PostTagMaps")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JustBlog.Core.Entities.Tag", "Tag")
                        .WithMany("PostTagMaps")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("JustBlog.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("JustBlog.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JustBlog.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("JustBlog.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JustBlog.Core.Entities.Category", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("JustBlog.Core.Entities.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("PostTagMaps");
                });

            modelBuilder.Entity("JustBlog.Core.Entities.Tag", b =>
                {
                    b.Navigation("PostTagMaps");
                });
#pragma warning restore 612, 618
        }
    }
}
